// packages/lit-app/src/views/cards.view.ts
import { cardBloc } from "@core/blocs/cards/card.bloc";
import type { Card } from "@core/blocs/cards/card.model";
import { cardStore } from "@core/blocs/cards/card.store";
import { notiBloc } from "@core/blocs/notifications/noti.bloc";
import { ValidationError } from "@core/helpers/validation";
import "@ui/components/cards-list.element.js";
import "@ui/components/text-input.element.js";
import { LitElement, html } from "lit";
import { state } from "lit/decorators.js";

export class CardsView extends LitElement {
	@state()
	private cards: readonly Card[] = [];

	unsubscribe!: () => void;

	async connectedCallback() {
		super.connectedCallback();

		this.unsubscribe = cardStore.subscribe((state) => {
			this.cards = state.filteredCards;
		});
		await cardBloc.getAllCards();
		notiBloc.showInfo("Cards loaded");
	}

	handleFilter = async (event: CustomEvent<string>) => {
		const query = event.detail;
		try {
			cardBloc.filterByName(query);
		} catch (error) {
			if (error instanceof ValidationError) {
				notiBloc.showWarning(error.errors.byName[0]);
			}
		}
	};

	disconnectedCallback(): void {
		this.unsubscribe();
		super.disconnectedCallback();
	}

	render() {
		return html`
            <h1>Lit Pokemóns</h1>
			<poke-text-input @on-submit="${this.handleFilter}" buttonText="Filter"></poke-text-input>
            <poke-cards-list .cards="${this.cards}"></poke-cards-list>
        `;
	}

	createRenderRoot() {
		return this;
	}
}

customElements.define("cards-view", CardsView);

// packages/vue-app/src/views/CardsView.vue
<script setup lang="ts">
import { cardBloc } from "@core/blocs/cards/card.bloc";
import { type CardBlocState, cardStore } from "@core/blocs/cards/card.store";
import { notiBloc } from "@core/blocs/notifications/noti.bloc";
import { ValidationError } from "@core/helpers/validation";
import "@ui/components/cards-list.element";
import "@ui/components/text-input.element";
import { onMounted, onUnmounted, ref } from "vue";

import type { CardList } from "@ui/components/cards-list.element";
import type { Ref } from "vue";

const cardListRef: Ref<CardList | null> = ref(null);

const filterByName = (event: { detail: string }) => {
	try {
		cardBloc.filterByName(event.detail);
	} catch (error) {
		if (error instanceof ValidationError) {
			notiBloc.showWarning(error.errors.byName[0]);
		}
	}
};

onMounted(async () => {
	const unsubscribeCardStore = cardStore.subscribe((state: CardBlocState) => {
		if (cardListRef.value) {
			cardListRef.value.cards = [...state.filteredCards];
		}
	});

	const cards = await cardBloc.getAllCards();
	notiBloc.showInfo("Cards loaded");

	if (cardListRef.value) {
		cardListRef.value.cards = [...cards];
	}

	onUnmounted(() => {
		unsubscribeCardStore();
	});
});
</script>

<template>
	<h1>Vue Pokemóns</h1>
	<poke-text-input buttonText="Filter" @on-submit="filterByName"></poke-text-input>
	<poke-cards-list ref="cardListRef"></poke-cards-list>
</template>
