// packages/react-app/src/App.jsx
import { useEffect, useRef, useState } from "react";
import { cardBloc } from "../../core-lib-ts/src/blocs/cards/card.bloc";
import { notiBloc } from "../../core-lib-ts/src/blocs/notifications/noti.bloc";
import "../../core-ui/src/components/cards-list.element.js";
import "../../core-ui/src/components/text-input.element.js";
import "./App.css";

function App() {
	const [cards, setCards] = useState([]);
	const cardListRef = useRef(null);

	useEffect(() => {
		const fetchCards = async () => {
			try {
				const allCards = await cardBloc.getAllCards();
				setCards(allCards);
				notiBloc.showInfo("Cards fetched successfully");
				notiBloc.store.subscribe((state) => console.log(state));
			} catch (error) {
				console.error("Error fetching cards:", error);
			}
		};

		fetchCards();
	}, []);

	useEffect(() => {
		if (cardListRef.current) {
			cardListRef.current.cards = cards;
		}
	}, [cards]);

	useEffect(() => {
		const textInput = document.querySelector("poke-text-input");
		if (textInput) {
			textInput.addEventListener("on-submit", handleFilter);
			return () => textInput.removeEventListener("on-submit", handleFilter);
		}
	}, []);

	const handleFilter = async (event) => {
		const query = event.detail;
		try {
			const filteredCards = cardBloc.filterByName(query);
			setCards(filteredCards);
		} catch (error) {
			console.error("Error filtering cards:", error);
		}
	};

	return (
		<>
			<main>
				<h1>React Pokemóns</h1>
				<poke-text-input buttonText="Filter" />
				<poke-cards-list ref={cardListRef} />
			</main>
		</>
	);
}

export default App;

// packages/vue-app/src/App.vue
<script setup>
import { onMounted, ref } from "vue";
import { cardBloc } from "../../core-lib-ts/src/blocs/cards/card.bloc";
import { notiBloc } from "../../core-lib-ts/src/blocs/notifications/noti.bloc";
import "../../core-ui/src/components/cards-list.element";
import "../../core-ui/src/components/text-input.element";

const cardListRef = ref(null);

const filterByName = ref((event) => {
	const filteredCards = cardBloc.filterByName(event.detail);
	if (cardListRef.value) {
		cardListRef.value.cards = filteredCards;
	}
});

onMounted(async () => {
	notiBloc.store.subscribe((state) => {
		console.log(JSON.stringify(state));
	});

	notiBloc.showInfo("Se mostrará?");

	const cards = await cardBloc.getAllCards();

	if (cardListRef.value) {
		cardListRef.value.cards = cards;
	}
});
</script>

<template>
  <h1>Vue Pokemóns</h1>
  <poke-text-input buttonText="Filter" @on-submit="filterByName"></poke-text-input>
  <poke-cards-list ref="cardListRef"></poke-cards-list>
</template>

<style scoped></style>
