// packages/lit-app/src/views/notification.view.ts
import type { Noti } from "@core/blocs/notifications/noti.model";
import {
	type NotiStoreState,
	notiStore,
} from "@core/blocs/notifications/noti.store";
import "@ui/components/noti.element";
import { LitElement, html } from "lit";
import { state } from "lit/decorators.js";

export class NotificationView extends LitElement {
	@state()
	private noti: Noti | null = null;

	unsubscribe!: () => void;

	connectedCallback(): void {
		super.connectedCallback();
		this.unsubscribe = notiStore.subscribe((state: NotiStoreState) => {
			this.noti = state.noti;
		});
	}

	disconnectedCallback(): void {
		this.unsubscribe();
		super.disconnectedCallback();
	}

	render() {
		return html`${
			this.noti &&
			html`<poke-notification msg="${this.noti.msg}" 
		                     type="${this.noti.type}" 
							 duration="${this.noti.duration}"></poke-notification>`
		}
          `;
	}

	createRenderRoot() {
		return this;
	}
}

customElements.define("notification-view", NotificationView);

// packages/react-app/src/views/NotificationView.tsx
import { notiStore } from "@core/blocs/notifications/noti.store";
import "@ui/components/noti.element";
import { useEffect, useState } from "react";

export function NotificationView() {
	const [notification, setNotification] = useState({
		msg: "",
		type: "INFO",
		duration: 3000,
	});

	useEffect(() => {
		const unsubscribe = notiStore.subscribe((state) => {
			if (state.noti) {
				setNotification({
					msg: state.noti.msg,
					type: state.noti.type,
					duration: state.noti.duration,
				});
			}
		});

		return () => {
			unsubscribe();
		};
	}, []);

	return (
		<poke-notification
			msg={notification.msg}
			type={notification.type}
			duration={notification.duration}
		></poke-notification>
	);
}
