// packages/vue-app/src/views/CardsView.vue
<script setup lang="ts">
import { cardBloc } from "@core/blocs/cards/card.bloc";
import { type CardBlocState, cardStore } from "@core/blocs/cards/card.store";
import { notiBloc } from "@core/blocs/notifications/noti.bloc";
import { ValidationError } from "@core/helpers/validation";
import "@ui/components/cards-list.element";
import "@ui/components/text-input.element";
import { onMounted, onUnmounted, ref } from "vue";

import type { CardList } from "@ui/components/cards-list.element";
import type { Ref } from "vue";

const cardListRef: Ref<CardList | null> = ref(null);

const filterByName = (event: { detail: string }) => {
	try {
		cardBloc.filterByName(event.detail);
	} catch (error) {
		if (error instanceof ValidationError) {
			notiBloc.showWarning(error.errors.byName[0]);
		}
	}
};

onMounted(async () => {
	const unsubscribeCardStore = cardStore.subscribe((state: CardBlocState) => {
		if (cardListRef.value) {
			cardListRef.value.cards = [...state.filteredCards];
		}
	});

	const cards = await cardBloc.getAllCards();
	notiBloc.showInfo("Cards loaded");

	if (cardListRef.value) {
		cardListRef.value.cards = [...cards];
	}

	onUnmounted(() => {
		unsubscribeCardStore();
	});
});
</script>

<template>
	<h1>Vue Pokemóns</h1>
	<poke-text-input buttonText="Filter" @on-submit="filterByName"></poke-text-input>
	<poke-cards-list ref="cardListRef"></poke-cards-list>
</template>

// packages/angular-app/src/app/views/cards/cards.view.ts
import { CommonModule } from "@angular/common";
import {
	CUSTOM_ELEMENTS_SCHEMA,
	Component,
	type OnDestroy,
	type OnInit,
} from "@angular/core";
import { cardBloc } from "@core/blocs/cards/card.bloc";
import type { Card } from "@core/blocs/cards/card.model";
import { cardStore } from "@core/blocs/cards/card.store";
import { notiBloc } from "@core/blocs/notifications/noti.bloc";
import { ValidationError } from "@core/helpers/validation";
import "@ui/components/cards-list.element.js";
import "@ui/components/text-input.element.js";

@Component({
	selector: "cards-view",
	standalone: true,
	imports: [CommonModule],
	templateUrl: "./cards.view.html",
	styleUrl: "./cards.view.css",
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class CardsView implements OnInit, OnDestroy {
	cards: ReadonlyArray<Card> = [];
	private unsubscribeCardStore: () => void;

	async ngOnInit() {
		this.cards = await cardBloc.getAllCards();
		notiBloc.showInfo("Cards Loaded");

		this.unsubscribeCardStore = cardStore.subscribe((state) => {
			this.cards = state.filteredCards;
		});
	}

	ngOnDestroy() {
		this.unsubscribeCardStore();
	}

	filterByName(e) {
		const name = e.target.value;
		try {
			cardBloc.filterByName(name);
		} catch (error) {
			if (error instanceof ValidationError) {
				notiBloc.showWarning(error.errors["byName"][0]);
			}
		}
	}
}
