// packages/vue-app/src/pages/Home.vue
<script setup>
import "@core-ui/components/cards-list.element";
import "@core-ui/components/text-input.element";
import { cardBloc } from "@core/blocs/cards/card.bloc";
import { notiBloc } from "@core/blocs/notifications/noti.bloc";
import { onMounted, ref } from "vue";

const cardListRef = ref(null);

const filterByName = (event) => {
	const filteredCards = cardBloc.filterByName(event.detail);
	if (cardListRef.value) {
		cardListRef.value.cards = filteredCards;
	}
};

onMounted(async () => {
	notiBloc.store.subscribe((state) => {
		console.log(JSON.stringify(state));
	});

	notiBloc.showInfo("Se mostrará?");

	const cards = await cardBloc.getAllCards();

	if (cardListRef.value) {
		cardListRef.value.cards = cards;
	}
});
</script>

<template>
  <main>
    <h1>Vue Pokemóns</h1>
    <poke-text-input buttonText="Filter" @on-submit="filterByName"></poke-text-input>
    <poke-cards-list ref="cardListRef"></poke-cards-list>
  </main>
</template>

// packages/react-app/src/pages/Home.tsx
import { cardBloc } from "@core/blocs/cards/card.bloc";
import { notiBloc } from "@core/blocs/notifications/noti.bloc";
import { notiStore } from "@core/blocs/notifications/noti.store";
import "@ui/components/cards-list.element.js";
import "@ui/components/text-input.element.js";
import { useEffect, useRef, useState } from "react";

function Home() {
	const [cards, setCards] = useState([]);
	const cardListRef = useRef(null);

	useEffect(() => {
		const fetchCards = async () => {
			try {
				const allCards = await cardBloc.getAllCards();
				setCards(allCards);
				notiBloc.showInfo("Cards fetched successfully");
				notiStore.subscribe((state) => console.log(state));
			} catch (error) {
				console.error("Error fetching cards:", error);
			}
		};

		fetchCards();
	}, []);

	useEffect(() => {
		if (cardListRef.current) {
			cardListRef.current.cards = cards;
		}
	}, [cards]);

	useEffect(() => {
		const textInput = document.querySelector("poke-text-input");
		if (textInput) {
			textInput.addEventListener("on-submit", handleFilter);
			return () => textInput.removeEventListener("on-submit", handleFilter);
		}
	}, []);

	const handleFilter = async (event: CustomEvent<string>) => {
		const query = event.detail;
		try {
			const filteredCards = cardBloc.filterByName(query);
			setCards(filteredCards);
		} catch (error) {
			console.error("Error filtering cards:", error);
		}
	};

	return (
		<main>
			<h1>React Pokemóns</h1>
			<poke-text-input buttonText="Filter" />
			<poke-cards-list ref={cardListRef} />
		</main>
	);
}

export default Home;
